### ISSUE TITLE
Please ask: Why my AX6 wireless is not displayed (not running)!

### ISSUE THREAD

**Issue by zxlhhyccc** [qosmio/nss-packages#11]
following items have been configured:
````
CONFIG_DEFAULT_kmod-ath11k-ahb=y
CONFIG_PACKAGE_kmod-ath=y
CONFIG_PACKAGE_kmod-ath11k=y
CONFIG_PACKAGE_kmod-ath11k-ahb=y
CONFIG_ATH11K_NSS_SUPPORT=y
CONFIG_ATH11K_MEM_PROFILE_512M=y
````

**Comment by qosmio** [comment]
Your hardware is detected. Something else is going on with your build. Please try building regular non-NSS build to ensure it's working first, before trying the NSS build.

Use the main branch of openwrt.

_Originally posted by @qosmio in https://github.com/qosmio/nss-packages/issues/10#issuecomment-1915113503_
