### ISSUE TITLE
kmod-qca-nss-drv-clmapmgr: Does not compile on GCC 13.

### ISSUE THREAD

**Issue by JuliusBairaktaris** [qosmio/nss-packages#14]
Hey, kmod-qca-nss-drv-clmapmgr does not currently build with GCC 13. I would appreciate it if you could fix it to make the repo future proof. 

Here are the logs: https://github.com/starraiderx/Qualcommax_NSS_Builder/actions/runs/8090898374

Regards,
Julius

**Comment by qosmio** [comment]
Was fixed as part of 8d54d726c2c04333b7f756c982f5bd9b6537139a
