### ISSUE TITLE
'kmod-qca-ovsmgr' does not exist. 

### ISSUE THREAD

**Issue by JuliusBairaktaris** [qosmio/nss-packages#18]
Since the commit 7e02d378bb5540c3cda49312f3cae8bcc2368337 I get the following error when building: 

`WARNING: Makefile 'package/feeds/nss_packages/qca-nss-ecm/Makefile' has a dependency on 'kmod-qca-ovsmgr', which does not exist. ` 

Kind regards.

**Comment by qosmio** [comment]
Should be fixed in latest commit
