### ISSUE TITLE
Can't start after selecting ath11k compile on ipq60xx

### ISSUE THREAD

**Issue by breeze303** [qosmio/nss-packages#23]
I suspect that the mac80211 in the ath11k called wifi-meshmgr lead to, even if I choose ATH11K_MEM_PROFILE_256M can not start, if you are interested I can pr to openwrt-ipq you to see if it can be repaired, do not select the ath11k then you can start normally!

**Comment by qosmio** [comment]
I'm afraid I'm not following. There's no trace/boot/dmesg logs. Not sure how I can help.

> I suspect that the mac80211 in the ath11k called wifi-meshmgr.

Mesh NSS really only works with NSS Firmware 11.4. Your `.config` must look like this

```
CONFIG_NSS_FIRMWARE_VERSION_11_4=y
# CONFIG_NSS_FIRMWARE_VERSION_12_1 is not set
```

To completley disable mesh, you must make the `.config` like so. it must start with `"#"` and end with `" is not set"`
```
# CONFIG_NSS_DRV_WIFI_MESH_ENABLE is not set
# CONFIG_PACKAGE_kmod-qca-nss-drv-wifi-meshmgr is not set
# CONFIG_ATH11K_NSS_MESH_SUPPORT is not set
# CONFIG_PACKAGE_MAC80211_MESH is not set
```

**Comment by breeze303** [comment]
> I'm afraid I'm not following. There's no trace/boot/dmesg logs. Not sure how I can help.
> 
> > I suspect that the mac80211 in the ath11k called wifi-meshmgr.
> 
> Mesh NSS really only works with NSS Firmware 11.4. Your must look like this`.config`
> 
> ```
> CONFIG_NSS_FIRMWARE_VERSION_11_4=y
> # CONFIG_NSS_FIRMWARE_VERSION_12_1 is not set
> ```
> 
> To completley disable mesh, you must make the like so. it must start with and end with `.config``"#"``" is not set"`
> 
> ```
> # CONFIG_NSS_DRV_WIFI_MESH_ENABLE is not set
> # CONFIG_PACKAGE_kmod-qca-nss-drv-wifi-meshmgr is not set
> # CONFIG_ATH11K_NSS_MESH_SUPPORT is not set
> # CONFIG_PACKAGE_MAC80211_MESH is not set
> ```

Thank you for your reply, I tested that it is indeed the mesh that is causing the unbootable issue, I see that in the ttl it's the memory part of the problem, I can't do a reproduction operation at the moment because the codebase was deleted by me
