### ISSUE TITLE
net/core/skbuff_recycle.c:635:9: error: 'h' undeclared (first use in this function)

### ISSUE THREAD

**Issue by biglihao** [qosmio/nss-packages#25]
>   CC      net/core/xdp.o
  CC      net/core/flow_offload.o
  CC      net/core/gro.o
  CC      net/core/netdev-genl.o
  CC      net/core/netdev-genl-gen.o
  CC      net/core/gso.o
  CC      net/core/sock_diag.o
  CC      net/core/net-sysfs.o
  CC      net/core/page_pool.o
  CC      net/core/net-procfs.o
  CC      net/core/fib_rules.o
  CC      net/core/selftests.o
  CC      net/core/lwtunnel.o
  CC      net/core/dst_cache.o
  CC      net/core/gro_cells.o
  CC      net/core/skmsg.o
  CC      net/core/sock_map.o
  CC      net/core/bpf_sk_storage.o
  CC      net/core/of_net.o
  CC      net/core/skbuff_recycle.o
net/core/skbuff_recycle.c: In function 'skb_recycler_print_all_lists':
net/core/skbuff_recycle.c:635:9: error: 'h' undeclared (first use in this function)
  635 |         h = &per_cpu(recycle_list, cpu);
      |         ^
net/core/skbuff_recycle.c:635:9: note: each undeclared identifier is reported only once for each function it appears in
make[9]: *** [scripts/Makefile.build:243: net/core/skbuff_recycle.o] Error 1
make[8]: *** [scripts/Makefile.build:480: net/core] Error 2
make[7]: *** [scripts/Makefile.build:480: net] Error 2
make[6]: *** [/home/ubuntu/immortalwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.30/Makefile:1913: .] Error 2
make[5]: *** [Makefile:234: __sub-make] Error 2
make[5]: Leaving directory '/home/ubuntu/immortalwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.30'
make[4]: *** [Makefile:23: /home/ubuntu/immortalwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.30/.modules] Error 2
make[4]: Leaving directory '/home/ubuntu/immortalwrt/target/linux/qualcommax'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/ubuntu/immortalwrt/target/linux'
time: target/linux/compile#2746.35#263.48#3084.01
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:32: target/linux/compile] Error 1
make[2]: Leaving directory '/home/ubuntu/immortalwrt'
make[1]: *** [target/Makefile:25: /home/ubuntu/immortalwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/ubuntu/immortalwrt'
make: *** [/home/ubuntu/immortalwrt/include/toplevel.mk:233: world] Error 2

 I am use the nss_packages repo and immortalwrt,my device is redmi ax6 . please help me with the error , thank you

**Comment by qosmio** [comment]
This is unrelated to nss packages located in this repository. Also, I don't manage `immortalwrt`, you have to build off my fork of OpenWRT https://github.com/qosmio/openwrt-ipq/tree/qualcommax-6.x-nss-wifi.
