### ISSUE TITLE
Cannot select subtarget other than ipq807x

### ISSUE THREAD

**Issue by JiaY-shi** [qosmio/nss-packages#29]
https://github.com/qosmio/nss-packages/blob/5fa030cfed30fdfec32f681c345fbf47d15d0fd3/firmware/nss-firmware/Makefile#L102

@qosmio After debugging, the problem is in this line, but I'm not very familiar with Makefile, so I don't know how to fix it.

**Comment by qosmio** [comment]
Closing

Merged in PRs:
[nss-firmware: fix building for IPQ60XX/IPQ50XX](174edae00a4efef4e4930fa6433a0ce5e8286472)
[qca-nss-macsec: add ipq6018 support](1d044076d9853dd51ab5c8806d99de476ec4fe4d)
