### ISSUE TITLE
NSS module compile errors after doing a NSS feeds update

### ISSUE THREAD

**Issue by vochong** [qosmio/nss-packages#4]
I did the latest nss feeds update and got errors when compiling the modules.

$ scripts/feeds update -f nss && scripts/feeds install -a -p nss

Updating feed 'nss' from 'https://github.com/qosmio/nss-packages.git;NSS-11.2-K5.15' ...
Already up to date.
Create index file './feeds/nss.index' 
Installing all packages from feed nss.

$ make target/clean
make[2]: Entering directory '/home/python/Venv/QOSMIO/openwrt-ip806x/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/home/python/Venv/QOSMIO/openwrt-ip806x/scripts/config'
time: target/linux/prereq#0.20#0.18#0.36
 make[1] target/clean
 make[2] -C target/linux clean

$ make package/{qca-nss-drv,qca-nss-clients,qca-nss-ecm}/{clean,compile} V=sc -j$(nproc)
make[2]: Entering directory '/home/python/Venv/QOSMIO/openwrt-ip806x/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/home/python/Venv/QOSMIO/openwrt-ip806x/scripts/config'
make[1]: Entering directory '/home/python/Venv/QOSMIO/openwrt-ip806x'
make[2]: Entering directory '/home/python/Venv/QOSMIO/openwrt-ip806x/feeds/nss/qca-nss-drv'
rm -rf /home/python/Venv/QOSMIO/openwrt-ip806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-2020-03-20-3cfb9f43
rm -f /home/python/Venv/QOSMIO/openwrt-ip806x/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/stamp/.qca-nss-drv_installed
rm -f /home/python/Venv/QOSMIO/openwrt-ip806x/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/packages/qca-nss-drv.list
make[2]: Leaving directory '/home/python/Venv/QOSMIO/openwrt-ip806x/feeds/nss/qca-nss-drv'
time: package/feeds/nss/qca-nss-drv/clean#0.17#0.21#0.34
make[1]: Leaving directory '/home/python/Venv/QOSMIO/openwrt-ip806x'
make[2]: Entering directory '/home/python/Venv/QOSMIO/openwrt-ip806x/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/home/python/Venv/QOSMIO/openwrt-ip806x/scripts/config'
make[1]: Entering directory '/home/python/Venv/QOSMIO/openwrt-ip806x'
make[2]: Entering directory '/home/python/Venv/QOSMIO/openwrt-ip806x/feeds/nss/qca-nss-gmac'
touch /home/python/Venv/QOSMIO/openwrt-ip806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-gmac-2021-04-20-17176794/.prepared_06ba6bf3c8ed032967bddedc01e3eeb7_6664517399ebbbc92a37c5bb081b5c53_check
. /home/python/Venv/QOSMIO/openwrt-ip806x/include/shell.sh; xzcat /home/python/Venv/QOSMIO/openwrt-ip806x/dl/qca-nss-gmac-2021-04-20-17176794.tar.xz | tar -C /home/python/Venv/QOSMIO/openwrt-ip806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-gmac-2021-04-20-17176794/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/. /home/python/Venv/QOSMIO/openwrt-ip806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-gmac-2021-04-20-17176794

Applying ./patches/0000-kernel-5.10-support.patch using plaintext: 
patching file ipq806x/nss_gmac_ctrl.c
patching file ipq806x/nss_gmac_ethtool.c
patching file ipq806x/nss_gmac_dev.c
patching file ipq806x/include/nss_gmac_network_interface.h
patching file ipq806x/nss_gmac_tx_rx_offload.c

Applying ./patches/0008-add-extra-logging.patch using plaintext: 
patching file ipq806x/nss_gmac_tx_rx_offload.c
patching file ipq806x/nss_gmac_ctrl.c
patching file ipq806x/nss_gmac_dev.c
patching file ipq806x/nss_gmac_ethtool.c
patching file ipq806x/nss_gmac_init.c
patching file ipq806x/nss_gmac_mdiobus.c

Applying ./patches/0009-add-tstamp-enable-func-ethtool.patch using plaintext: 
patching file ipq806x/include/nss_gmac_dev.h
patching file ipq806x/nss_gmac_ctrl.c
patching file ipq806x/nss_gmac_ethtool.c
touch /home/python/Venv/QOSMIO/openwrt-ip806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-gmac-2021-04-20-17176794/.prepared_06ba6bf3c8ed032967bddedc01e3eeb7_6664517399ebbbc92a37c5bb081b5c53
rm -f /home/python/Venv/QOSMIO/openwrt-ip806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-gmac-2021-04-20-17176794/.configured_*
rm -f /home/python/Venv/QOSMIO/openwrt-ip806x/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/stamp/.qca-nss-gmac_installed
(cd /home/python/Venv/QOSMIO/openwrt-ip806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-gmac-2021-04-20-17176794/./; if [ -x ./configure ]; then find /home/python/Venv/QOSMIO/openwrt-ip806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-gmac-2021-04-20-17176794/ -name config.guess | xargs -r chmod u+w; find /home/python/Venv/QOSMIO/openwrt-ip806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-gmac-2021-04-20-17176794/ -name config.guess | xargs -r -n1 cp --remove-destination /home/python/Venv/QOSMIO/openwrt-ip806x/scripts/config.guess; find /home/python/Venv/QOSMIO/openwrt-ip806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-gmac-2021-04-20-17176794/ -name config.sub | xargs -r chmod u+w; find /home/python/Venv/QOSMIO/openwrt-ip806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-gmac-2021-04-20-17176794/ -name config.sub | xargs -r -n1 cp --remove-destination /home/python/Venv/QOSMIO/openwrt-ip806x/scripts/config.sub; AR="arm-openwrt-linux-muslgnueabi-gcc-ar" AS="arm-openwrt-linux-muslgnueabi-gcc -c -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/home/python/Venv/QOSMIO/openwrt-ip806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-gmac-2021-04-20-17176794=qca-nss-gmac-2021-04-20-17176794 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=arm-openwrt-linux-muslgnueabi-ld NM="arm-openwrt-linux-muslgnueabi-gcc-nm" CC="arm-openwrt-linux-muslgnueabi-gcc" GCC="arm-openwrt-linux-muslgnueabi-gcc" CXX="arm-openwrt-linux-muslgnueabi-g++" RANLIB="arm-openwrt-linux-muslgnueabi-gcc-ranlib" STRIP=arm-openwrt-linux-muslgnueabi-strip OBJCOPY=arm-openwrt-linux-muslgnueabi-objcopy OBJDUMP=arm-openwrt-linux-muslgnueabi-objdump SIZE=arm-openwrt-linux-muslgnueabi-size CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/home/python/Venv/QOSMIO/openwrt-ip806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-gmac-2021-04-20-17176794=qca-nss-gmac-2021-04-20-17176794 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DCONFIG_NSS_DEBUG_LEVEL=4 -I/home/python/Venv/QOSMIO/openwrt-ip806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-gmac-2021-04-20-17176794/nss_hal/include -I/home/python/Venv/QOSMIO/openwrt-ip806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-gmac-2021-04-20-17176794/nss_hal/ipq806x" CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/home/python/Venv/QOSMIO/openwrt-ip806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-gmac-2021-04-20-17176794=qca-nss-gmac-2021-04-20-17176794 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DCONFIG_NSS_DEBUG_LEVEL=4 -I/home/python/Venv/QOSMIO/openwrt-ip806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-gmac-2021-04-20-17176794/nss_hal/include -I/home/python/Venv/QOSMIO/openwrt-ip806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-gmac-2021-04-20-17176794/nss_hal/ipq806x" CPPFLAGS="-I/home/python/Venv/QOSMIO/openwrt-ip806x/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-11.3.0_musl_eabi/usr/include -I/home/python/Venv/QOSMIO/openwrt-ip806x/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-11.3.0_musl_eabi/include/fortify -I/home/python/Venv/QOSMIO/openwrt-ip806x/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-11.3.0_musl_eabi/include " LDFLAGS="-L/home/python/Venv/QOSMIO/openwrt-ip806x/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-11.3.0_musl_eabi/usr/lib -L/home/python/Venv/QOSMIO/openwrt-ip806x/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-11.3.0_musl_eabi/lib -znow -zrelro "   ./configure --target=arm-openwrt-linux --host=arm-openwrt-linux --build=x86_64-pc-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls  ; fi; )
touch /home/python/Venv/QOSMIO/openwrt-ip806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-gmac-2021-04-20-17176794/.configured_68b329da9893e34099c7d8ad5cb9c940
make[2]: *** No rule to make target '/home/python/Venv/QOSMIO/openwrt-ip806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/linux-5.15.69/.config', needed by '/home/python/Venv/QOSMIO/openwrt-ip806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-gmac-2021-04-20-17176794/.built'.  Stop.
make[2]: Leaving directory '/home/python/Venv/QOSMIO/openwrt-ip806x/feeds/nss/qca-nss-gmac'
time: package/feeds/nss/qca-nss-gmac/compile#0.23#0.31#1.65
    ERROR: package/feeds/nss/qca-nss-gmac failed to build.
make[1]: *** [package/Makefile:116: package/feeds/nss/qca-nss-gmac/compile] Error 1
make[1]: Leaving directory '/home/python/Venv/QOSMIO/openwrt-ip806x'
make: *** [/home/python/Venv/QOSMIO/openwrt-ip806x/include/toplevel.mk:231: package/qca-nss-drv/compile] Error 2

**Comment by qosmio** [comment]
After doing a “target/clean”, everything kernel related gets wiped, including the kernel. You have to compile it again before you can build any modules. That’s how the openwrt build system works.

```bash
# single command that will build everything required + the final image. 
make world -j$(nproc)

# clean the kernel (this should normally be automatic when you’re upgrading kernels, but it’s good run if you’ve made any kernel related changes)
make target/clean

# compile kernel and headers.
make target/compile -j$(nproc)

# if you want to run one command to clean and compile the kernel.
make target/{clean,compile} -j$(nproc)

# clean and compile nss related packages
make package/{qca-nss-gmac,qca-nss-drv,qca-mcs,qca-nss-clients,qca-nss-ecm,nss-ifb}/{clean,compile} -j$(nproc)

# if everything compiled properly, then build remaining packages, and create final firmware image.
make package/{compile,install} target/install -j$(nproc)
```

**Comment by vochong** [comment]
Thank you very much Qosmio.
